# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'computer_screen_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import files_rc


class Ui_ComputerScreen(object):
    def setupUi(self, ComputerScreen):
        ComputerScreen.setObjectName("ComputerScreen")
        ComputerScreen.resize(600, 600)
        ComputerScreen.setMinimumSize(QtCore.QSize(600, 600))
        ComputerScreen.setMaximumSize(QtCore.QSize(600, 600))
        self.centralwidget = QtWidgets.QWidget(ComputerScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.background_img = QtWidgets.QLabel(self.centralwidget)
        self.background_img.setGeometry(QtCore.QRect(0, 0, 600, 600))
        self.background_img.setMinimumSize(QtCore.QSize(600, 600))
        self.background_img.setMaximumSize(QtCore.QSize(600, 600))
        self.background_img.setText("")
        self.background_img.setPixmap(QtGui.QPixmap(":/background/images/gamer_room_fase/computer_screen.png"))
        self.background_img.setScaledContents(True)
        self.background_img.setObjectName("background_img")
        self.open_file = QtWidgets.QPushButton(self.centralwidget)
        self.open_file.setGeometry(QtCore.QRect(454, 162, 51, 51))
        self.open_file.setStyleSheet("background-color: rgba(0,0,0,0);")
        self.open_file.setText("")
        self.open_file.setObjectName("open_file")
        self.back_to_room_lb = QtWidgets.QLabel(self.centralwidget)
        self.back_to_room_lb.setGeometry(QtCore.QRect(10, 0, 91, 101))
        self.back_to_room_lb.setText("")
        self.back_to_room_lb.setPixmap(QtGui.QPixmap(":/background/images/gamer_room_fase/gamer_room_img_nobg.png"))
        self.back_to_room_lb.setScaledContents(True)
        self.back_to_room_lb.setObjectName("back_to_room_lb")
        self.back_to_room_btn = QtWidgets.QPushButton(self.centralwidget)
        self.back_to_room_btn.setGeometry(QtCore.QRect(10, 0, 101, 101))
        self.back_to_room_btn.setStyleSheet("background-color: rgba(0,0,0,0);")
        self.back_to_room_btn.setText("")
        self.back_to_room_btn.setObjectName("back_to_room_btn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 50, 47, 13))
        self.label.setObjectName("label")
        ComputerScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(ComputerScreen)
        QtCore.QMetaObject.connectSlotsByName(ComputerScreen)

    def retranslateUi(self, ComputerScreen):
        _translate = QtCore.QCoreApplication.translate
        ComputerScreen.setWindowTitle(_translate("ComputerScreen", "MainWindow"))
        self.label.setText(_translate("ComputerScreen", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ComputerScreen = QtWidgets.QMainWindow()
    ui = Ui_ComputerScreen()
    ui.setupUi(ComputerScreen)
    ComputerScreen.show()
    sys.exit(app.exec_())
