# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gamer_room_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import files_rc

class Ui_GamerRoom(object):
    def setupUi(self, GamerRoom):
        GamerRoom.setObjectName("GamerRoom")
        GamerRoom.resize(600, 600)
        GamerRoom.setMinimumSize(QtCore.QSize(600, 600))
        self.centralwidget = QtWidgets.QWidget(GamerRoom)
        self.centralwidget.setObjectName("centralwidget")
        self.bg_img_lb = QtWidgets.QLabel(self.centralwidget)
        self.bg_img_lb.setGeometry(QtCore.QRect(0, 0, 600, 600))
        self.bg_img_lb.setMinimumSize(QtCore.QSize(600, 600))
        self.bg_img_lb.setMaximumSize(QtCore.QSize(600, 600))
        self.bg_img_lb.setText("")
        self.bg_img_lb.setPixmap(QtGui.QPixmap(":/background/images/gamer_room_img.png"))
        self.bg_img_lb.setScaledContents(True)
        self.bg_img_lb.setObjectName("bg_img_lb")
        self.open_pc_btn = QtWidgets.QPushButton(self.centralwidget)
        self.open_pc_btn.setGeometry(QtCore.QRect(200, 250, 91, 81))
        self.open_pc_btn.setStyleSheet("background-color: rgba(0,0,0,0);")
        self.open_pc_btn.setText("")
        self.open_pc_btn.setObjectName("open_pc_btn")
        GamerRoom.setCentralWidget(self.centralwidget)

        self.retranslateUi(GamerRoom)
        QtCore.QMetaObject.connectSlotsByName(GamerRoom)

    def retranslateUi(self, GamerRoom):
        _translate = QtCore.QCoreApplication.translate
        GamerRoom.setWindowTitle(_translate("GamerRoom", "MainWindow"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GamerRoom = QtWidgets.QMainWindow()
    ui = Ui_GamerRoom()
    ui.setupUi(GamerRoom)
    GamerRoom.show()
    sys.exit(app.exec_())
