# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plant_livingroom_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlantRoom(object):
    def setupUi(self, PlantRoom):
        PlantRoom.setObjectName("PlantRoom")
        PlantRoom.resize(600, 600)
        PlantRoom.setMinimumSize(QtCore.QSize(600, 600))
        PlantRoom.setMaximumSize(QtCore.QSize(600, 600))
        self.centralwidget = QtWidgets.QWidget(PlantRoom)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 600, 600))
        self.label.setMinimumSize(QtCore.QSize(600, 600))
        self.label.setMaximumSize(QtCore.QSize(600, 600))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/background/images/plant_room_img.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        PlantRoom.setCentralWidget(self.centralwidget)

        self.retranslateUi(PlantRoom)
        QtCore.QMetaObject.connectSlotsByName(PlantRoom)

    def retranslateUi(self, PlantRoom):
        _translate = QtCore.QCoreApplication.translate
        PlantRoom.setWindowTitle(_translate("PlantRoom", "MainWindow"))
import files_rc_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PlantRoom = QtWidgets.QMainWindow()
    ui = Ui_PlantRoom()
    ui.setupUi(PlantRoom)
    PlantRoom.show()
    sys.exit(app.exec_())
