# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'two_story_house_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import files_rc


class Ui_TwoStoryHouse(object):
    def setupUi(self, TwoStoryHouse):
        TwoStoryHouse.setObjectName("TwoStoryHouse")
        TwoStoryHouse.resize(600, 600)
        TwoStoryHouse.setMinimumSize(QtCore.QSize(600, 600))
        TwoStoryHouse.setMaximumSize(QtCore.QSize(600, 600))
        self.centralwidget = QtWidgets.QWidget(TwoStoryHouse)
        self.centralwidget.setObjectName("centralwidget")
        self.background_lb = QtWidgets.QLabel(self.centralwidget)
        self.background_lb.setGeometry(QtCore.QRect(0, 0, 600, 600))
        self.background_lb.setMinimumSize(QtCore.QSize(600, 600))
        self.background_lb.setMaximumSize(QtCore.QSize(600, 600))
        self.background_lb.setText("")
        self.background_lb.setPixmap(QtGui.QPixmap(":/background/images/futuristic_plants_room_img.webp"))
        self.background_lb.setScaledContents(True)
        self.background_lb.setObjectName("background_lb")
        self.glitch_frame = QtWidgets.QFrame(self.centralwidget)
        self.glitch_frame.setGeometry(QtCore.QRect(0, 0, 601, 601))
        self.glitch_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.glitch_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.glitch_frame.setObjectName("glitch_frame")
        self.glitch_lb = QtWidgets.QLabel(self.glitch_frame)
        self.glitch_lb.setGeometry(QtCore.QRect(-4, 2, 601, 601))
        self.glitch_lb.setText("")
        self.glitch_lb.setPixmap(QtGui.QPixmap(":/background/images/glitch_gif.gif"))
        self.glitch_lb.setScaledContents(True)
        self.glitch_lb.setObjectName("glitch_lb")
        TwoStoryHouse.setCentralWidget(self.centralwidget)

        self.retranslateUi(TwoStoryHouse)
        QtCore.QMetaObject.connectSlotsByName(TwoStoryHouse)

    def retranslateUi(self, TwoStoryHouse):
        _translate = QtCore.QCoreApplication.translate
        TwoStoryHouse.setWindowTitle(_translate("TwoStoryHouse", "MainWindow"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TwoStoryHouse = QtWidgets.QMainWindow()
    ui = Ui_TwoStoryHouse()
    ui.setupUi(TwoStoryHouse)
    TwoStoryHouse.show()
    sys.exit(app.exec_())
