# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shelf_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import files_rc

class Ui_shelf_window(object):
    def setupUi(self, shelf_window):
        shelf_window.setObjectName("shelf_window")
        shelf_window.resize(600, 600)
        shelf_window.setMinimumSize(QtCore.QSize(600, 600))
        shelf_window.setMaximumSize(QtCore.QSize(600, 600))
        self.centralwidget = QtWidgets.QWidget(shelf_window)
        self.centralwidget.setObjectName("centralwidget")
        self.bg_img_label = QtWidgets.QLabel(self.centralwidget)
        self.bg_img_label.setGeometry(QtCore.QRect(0, 0, 600, 600))
        self.bg_img_label.setMinimumSize(QtCore.QSize(600, 600))
        self.bg_img_label.setMaximumSize(QtCore.QSize(600, 600))
        self.bg_img_label.setText("")
        self.bg_img_label.setPixmap(QtGui.QPixmap(":/background/images/two_story_house_fase/book_shelf.png"))
        self.bg_img_label.setScaledContents(True)
        self.bg_img_label.setObjectName("bg_img_label")
        self.back_room_btn = QtWidgets.QPushButton(self.centralwidget)
        self.back_room_btn.setGeometry(QtCore.QRect(0, 0, 101, 111))
        self.back_room_btn.setStyleSheet("background-color: rgba(0,0,0,0);")
        self.back_room_btn.setText("")
        self.back_room_btn.setObjectName("back_room_btn")
        self.back_room_lb = QtWidgets.QLabel(self.centralwidget)
        self.back_room_lb.setGeometry(QtCore.QRect(0, 10, 101, 101))
        self.back_room_lb.setText("")
        self.back_room_lb.setPixmap(QtGui.QPixmap(":/background/images/two_story_house_fase/two_story_house_img_nobg.png"))
        self.back_room_lb.setScaledContents(True)
        self.back_room_lb.setObjectName("back_room_lb")
        self.bg_img_label.raise_()
        self.back_room_lb.raise_()
        self.back_room_btn.raise_()
        shelf_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(shelf_window)
        QtCore.QMetaObject.connectSlotsByName(shelf_window)

    def retranslateUi(self, shelf_window):
        _translate = QtCore.QCoreApplication.translate
        shelf_window.setWindowTitle(_translate("shelf_window", "MainWindow"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    shelf_window = QtWidgets.QMainWindow()
    ui = Ui_shelf_window()
    ui.setupUi(shelf_window)
    shelf_window.show()
    sys.exit(app.exec_())
